-- name: InsertUser :exec
INSERT INTO USERS(USERNAME, EMAIL, IS_ADMIN, USER_PASSWORD, CREATED_AT) VALUES (?,?,?,?,?);

-- name: GetUsers :one
SELECT * FROM USERS WHERE USERNAME LIKE (?) OR EMAIL LIKE (?);

-- name: IsAdmin :one 
SELECT * FROm USERS WHERE USERNAME LIKE (?) OR EMAIL LIKE (?) AND IS_ADMIN = TRUE;

-- name: DeleteUser :exec
DELETE FROM USERS WHERE USERNAME LIKE (?) OR EMAIL LIKE (?);

-- name: UpdateUser :exec
UPDATE USERS 
SET USERNAME = (?), EMAIL = (?), USER_PASSWORD = (?)
WHERE USERNAME LIKE (?) OR EMAIL LIKE (?)