// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: queries.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM USERS WHERE USERNAME LIKE (?) OR EMAIL LIKE (?)
`

type DeleteUserParams struct {
	Username string
	Email    string
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteUser, arg.Username, arg.Email)
	return err
}

const getUsers = `-- name: GetUsers :one
SELECT username, email, user_password FROM USERS WHERE USERNAME LIKE (?) OR EMAIL LIKE (?)
`

type GetUsersParams struct {
	Username string
	Email    string
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUsers, arg.Username, arg.Email)
	var i User
	err := row.Scan(&i.Username, &i.Email, &i.UserPassword)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO USERS(USERNAME, EMAIL, USER_PASSWORD) VALUES (?,?,?)
`

type InsertUserParams struct {
	Username     string
	Email        string
	UserPassword string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.Username, arg.Email, arg.UserPassword)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE USERS 
SET USERNAME = (?), EMAIL = (?), USER_PASSWORD = (?)
WHERE USERNAME LIKE (?) OR EMAIL LIKE (?)
`

type UpdateUserParams struct {
	Username     string
	Email        string
	UserPassword string
	Username_2   string
	Email_2      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.UserPassword,
		arg.Username_2,
		arg.Email_2,
	)
	return err
}
